
language: c
os: osx
sudo: true
env:
    global:
        - CODECOV_TOKEN="fb5641ce-5938-4a57-8265-5c08a1a0d4f7"
        - HOMEBREW_NO_AUTO_UPDATE=1
        - HOMEBREW_NO_INSTALL_CLEANUP=1
branches:
    only:
        - master
install:
    - brew install snaipe/soft/criterion
    - sudo touch /tmp/printf
before_script:
    - make test CV=1
    - make MAIN=tests/srcs/empty_env_dup_sys_env_test.c CV=1 NAME=emptyenvtest
    - env
script:
    - ./tests/minitest --verbose
    - env -i ./tests/minitest --verbose
    - env -i ./emptyenvtest
after_success:
    - make gcov
    - bash <(curl -s https://codecov.io/bash) -X gcov
after_failure:
    - env
